### ISSUE TITLE
uh. hmm?

### ISSUE THREAD

**Issue by jhfhngj** [oXo23/Nex#3]
i need an example please, imma try to make a program to see your compiler.

**Comment by jhfhngj** [comment]
actually i did it alr but where is the new program

**Comment by oXo23** [comment]
> actually i did it alr but where is the new program

wdym?

**Comment by jhfhngj** [comment]
ive made a prog and compiled it. isnt there supposed to be an app?

**Comment by oXo23** [comment]
Actually the type of compiler Nex uses is a s2s compiler (souce-to-source compiler) it translates it self to python...

But i well be working on it making an app..

**Comment by oXo23** [comment]
> ive made a prog and compiled it. isnt there supposed to be an app?

I have added this feature; it only supports windows for now... I well upgrade it even more in the future

**Comment by jhfhngj** [comment]
Oh ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jhfhngj** [comment]
well i have wine so sure ill clone the new one

**Comment by jhfhngj** [comment]
ok where is the compiled.exe

**Comment by oXo23** [comment]
> ok where is the compiled.exe

download the latest version of nex, and try making a new prog and compile it

**Comment by oXo23** [comment]
> > ok where is the compiled.exe
> 
> download the latest version of nex, and try making a new prog and compile it

i meant the latest version of Qweil

**Comment by jhfhngj** [comment]
yip thx
