### ISSUE TITLE
Compiler not compiling

### ISSUE THREAD

**Issue by jhfhngj** [oXo23/Nex#4]
I have made a program, and tried to bring it thru the compiler. It's not compiling (I have Ubuntu so I have Wine)

**Comment by oXo23** [comment]
<h1>Send me the following:</h1>
<hr>
<li>Send me the .nex script, send it over my email esuper223@gmail.com if your nex script is private</li>
<li>Did you run the nex compiler through a windows 11/10 environment?</li>
<li>Your python version</li>

**Comment by oXo23** [comment]
> I have made a program, and tried to bring it thru the compiler. It's not compiling (I have Ubuntu so I have Wine)

<h1>Hello!</h1>
<hr>
<p>I have fixed the error, check the releases tab, BUILD5 is the latest (and also the release where I fixed the bug) and download it!</p>
<hr>
<h3> Happy coding with Nex! </h3>

**Comment by oXo23** [comment]
> I have made a program, and tried to bring it thru the compiler. It's not compiling (I have Ubuntu so I have Wine)

Also compiling to an app on Linux is still not supported so instead either use Nex on windows (you still won't make a Linux app, even if you ran it at windows, it well still make an .exe which is a windows executable) or if you just want to execute the .nex script with converting it to a windows app, try:

```bat
rem main.py is the Nex compiler main script
python main.py script.nex -NC
```

the -NC switch is to skip compiling and just run the .nex script raw.
